### ISSUE TITLE
gen_cjk produces invalid characters

### ISSUE THREAD

**Issue by pondrejk** [omaciel/fauxfactory#118] opened 2021-02-25 13:00 UTC
...for example:  '䮯ᅰ𑻨겡𘀒썎洆랲鿂抲ᣙᾇ𘍅堸𓄂컷幂習䉕ꈅ𘨣',
this causes intermittent failures in several robottelo tests

**Comment by omaciel** [comment] 2021-03-19 20:31
@pondrejk can you take a look at the changes I made with dc9f7f6 and see if the problem is resolved?

**Comment by dosas** [comment] 2024-03-26 14:07
@pondrejk I am observing similar problems especially with https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/api/test_user.py#L224 (I saw you added a fix there but IMHO the tests are still flakey)

Did you have any chance testing these changes mentioned above. Speaking of release there are many changes that have not been released.  @omaciel Is there any chance we can get a new release?

**Comment by omaciel** [comment] 2024-03-26 23:09
Hey @dosas  I just published a new version 3.1.1. Can you take it for a spin, please?

**Comment by dosas** [comment] 2024-03-27 07:53
@omaciel Thank you for the fast reply and release. With this release I'm not getting the issues I had before.

**Comment by omaciel** [comment] 2024-03-27 13:02
Awesome. I'm going to close this issue then, but please do feel free to reopen it if you disagree.

**Closed by omaciel** 2024-03-27 13:02 UTC
